CREATE DATABASE IF NOT EXISTS RENTACAR;
USE RENTACAR;

CREATE TABLE cliente (
  id_cliente INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(120) NOT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
  CHECK (estado IN ('ACTIVO','INACTIVO'))
);
